model:
  model_name: DECODER_1 
  mlp_layers: [32, 64, 32, 9]
  decoder_channels: [32, 64, 32, 1]

training:
  learning_rate: 0.001
  epochs: 1000
  batch_size: 32
  patience : 50
  loss: "mse"

dataset:
  dataset_name: "20250428175523" # dataset 2
  dataset_format: "v1" #v1 classical loss, v2 FEM-informed

prepare:
  features: ["distances_x", "distances_y", "plaque_epaisseurs","materiaux"]
  train_test_split: 0.2
  val_test_split: 0.5
  seed: 42
  
  